# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Ui_MainWindow.ui',
# licensing of 'Ui_MainWindow.ui' applies.
#
# Created: Thu Nov  7 21:22:46 2019
#      by: pyside2-uic  running on PySide2 5.13.0
#
# WARNING! All changes made in this file will be lost!

from PySide2 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(257, 224)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.saveBtn = QtWidgets.QPushButton(self.centralwidget)
        self.saveBtn.setObjectName("saveBtn")
        self.horizontalLayout.addWidget(self.saveBtn)
        self.preBtn = QtWidgets.QPushButton(self.centralwidget)
        self.preBtn.setObjectName("preBtn")
        self.horizontalLayout.addWidget(self.preBtn)
        self.nextBtn = QtWidgets.QPushButton(self.centralwidget)
        self.nextBtn.setObjectName("nextBtn")
        self.horizontalLayout.addWidget(self.nextBtn)
        self.verticalLayout_2.addLayout(self.horizontalLayout)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.jumpSpinBox = QtWidgets.QSpinBox(self.centralwidget)
        self.jumpSpinBox.setObjectName("jumpSpinBox")
        self.horizontalLayout_3.addWidget(self.jumpSpinBox)
        self.jumpBtn = QtWidgets.QPushButton(self.centralwidget)
        self.jumpBtn.setObjectName("jumpBtn")
        self.horizontalLayout_3.addWidget(self.jumpBtn)
        self.line = QtWidgets.QFrame(self.centralwidget)
        self.line.setFrameShape(QtWidgets.QFrame.VLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.horizontalLayout_3.addWidget(self.line)
        self.skipCheckBox = QtWidgets.QCheckBox(self.centralwidget)
        self.skipCheckBox.setObjectName("skipCheckBox")
        self.horizontalLayout_3.addWidget(self.skipCheckBox)
        self.verticalLayout_2.addLayout(self.horizontalLayout_3)
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.predictBtn = QtWidgets.QPushButton(self.centralwidget)
        self.predictBtn.setObjectName("predictBtn")
        self.horizontalLayout_4.addWidget(self.predictBtn)
        self.autoPredictCheckBox = QtWidgets.QCheckBox(self.centralwidget)
        self.autoPredictCheckBox.setObjectName("autoPredictCheckBox")
        self.horizontalLayout_4.addWidget(self.autoPredictCheckBox)
        self.verticalLayout_2.addLayout(self.horizontalLayout_4)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setObjectName("label")
        self.horizontalLayout_2.addWidget(self.label)
        self.lableLineEdit = QtWidgets.QLineEdit(self.centralwidget)
        font = QtGui.QFont()
        font.setFamily("Consolas")
        font.setPointSize(16)
        font.setWeight(50)
        font.setBold(False)
        self.lableLineEdit.setFont(font)
        self.lableLineEdit.setAlignment(QtCore.Qt.AlignCenter)
        self.lableLineEdit.setObjectName("lableLineEdit")
        self.horizontalLayout_2.addWidget(self.lableLineEdit)
        self.enterBtn = QtWidgets.QPushButton(self.centralwidget)
        self.enterBtn.setObjectName("enterBtn")
        self.horizontalLayout_2.addWidget(self.enterBtn)
        self.verticalLayout_2.addLayout(self.horizontalLayout_2)
        self.groupBox = QtWidgets.QGroupBox(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.groupBox.sizePolicy().hasHeightForWidth())
        self.groupBox.setSizePolicy(sizePolicy)
        self.groupBox.setObjectName("groupBox")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.groupBox)
        self.verticalLayout.setObjectName("verticalLayout")
        self.imgLabel = QtWidgets.QLabel(self.groupBox)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.imgLabel.sizePolicy().hasHeightForWidth())
        self.imgLabel.setSizePolicy(sizePolicy)
        self.imgLabel.setAlignment(QtCore.Qt.AlignCenter)
        self.imgLabel.setObjectName("imgLabel")
        self.verticalLayout.addWidget(self.imgLabel)
        self.verticalLayout_2.addWidget(self.groupBox)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 257, 21))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(QtWidgets.QApplication.translate("MainWindow", "MainWindow", None, -1))
        self.saveBtn.setText(QtWidgets.QApplication.translate("MainWindow", "儲存", None, -1))
        self.preBtn.setText(QtWidgets.QApplication.translate("MainWindow", "上一個", None, -1))
        self.nextBtn.setText(QtWidgets.QApplication.translate("MainWindow", "下一個", None, -1))
        self.jumpBtn.setText(QtWidgets.QApplication.translate("MainWindow", "跳", None, -1))
        self.skipCheckBox.setText(QtWidgets.QApplication.translate("MainWindow", "跳過已標記", None, -1))
        self.predictBtn.setText(QtWidgets.QApplication.translate("MainWindow", "預測", None, -1))
        self.autoPredictCheckBox.setText(QtWidgets.QApplication.translate("MainWindow", "自動預測", None, -1))
        self.label.setText(QtWidgets.QApplication.translate("MainWindow", "Label: ", None, -1))
        self.enterBtn.setText(QtWidgets.QApplication.translate("MainWindow", "確認", None, -1))
        self.groupBox.setTitle(QtWidgets.QApplication.translate("MainWindow", "GroupBox", None, -1))
        self.imgLabel.setText(QtWidgets.QApplication.translate("MainWindow", "TextLabel", None, -1))

